title: IVFDF 2019
description: > # this means to ignore newlines until "baseurl:"
  The Inter Varsity Folk Dance Festival comes to Edinburgh in 2019! Hosted  by the Edinburgh University New Scotland Country Dance Society, it promises a weekend of music, dancing, workshops and other shenanigans.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ivfdf2019.org.uk" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2019_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: https://www.facebook.com/IVFDF2019/

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2019_pages']

collections:
  - 2019_team
  - 2019_bands
  - 2019_otherevents

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/IVFDF2019/

# Build settings
markdown: kramdown
permalink: pretty
